# Change these first
owner: Hajorda # Your GitHub organization or username, where this repository lives
repo:  KauwelaUptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: MCJ
    url: https://www.modelcj.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://hajorda.github.io/KauwelaUptime/
  baseUrl: /KauwelaUptime
  logoUrl: https://media.discordapp.net/attachments/984469722500329474/1076536703365435522/image.png
  name: Hajorda
  introTitle: "**KauwelaBot** is an Discord bot built with Java and You can check to status of the bot from here."
  introMessage:
  navbar:
    - title: Support Server
      href: https://discord.gg/jXpT9rtHMN
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
